#!/bin/bash

if [ "$1" = "init" ]; then
	mkdir ../data/story/mission/$2
	cp templates/mission/* ../data/story/mission/$2/
fi

if [ "$1" = "refresh" ]; then
	cd templates/mission
	for d in ../../../data/story/mission/*; do
		cp `ls | egrep -v '^\_.*$'` $d
	done
fi